### ISSUE TITLE
[BUG] Cloud buttons do nothing

### ISSUE THREAD

**Issue by LukeT** [xeonr/sagl-launcher#35]
**Describe the bug**
- The get started button does nothing
- When login times out, the back button does nothing.

**To Reproduce**
1. Login with cloud
2. Click on 'Click get started'
3. ...
4. rip

**Expected behavior**
It does something.

**Screenshots**
![image](https://user-images.githubusercontent.com/2203091/120050194-73d2b600-c014-11eb-9811-903fb20e0ade.png)
![image](https://user-images.githubusercontent.com/2203091/120050313-dd52c480-c014-11eb-829e-b0439d0d1e32.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by tmfksoft** [comment]
Fixed in the public release 1.1.3.
