### ISSUE TITLE
Gallery is blank

### ISSUE THREAD

**Issue by mikecnr** [xeonr/sagl-launcher#40]
My gallery is entirely blank

![image](https://user-images.githubusercontent.com/2178717/120112661-9ed11d00-c16e-11eb-91b2-7c0f88ac40d9.png)

**Comment by tmfksoft** [comment]
I'm still unable to replicate this and plan to sit down and investigate this properly. It utilises the same code as custom backgrounds, so they should work fine.

**Comment by tmfksoft** [comment]
Fixed in upcoming release.
