### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by V3NO-M** [xeonr/sagl-launcher#45]
**Describe the bug**
Pressing the "Get Started" Button won't do anything after logging into Discord Cloud. 

**To Reproduce**
1. Go to 'Settings'
2. Click on 'SA:GL Cloud'
3. Click on 'Log in With Discord'
4. Click on 'GET STARTED'
5. It's stuck on the same page. -Error

**Expected behavior**
Maybe the 'GET STARTED' Button hasn't assigned anything to do.

**Screenshots**
![Screenshot (1)](https://user-images.githubusercontent.com/61425872/121471262-33f4c280-c974-11eb-948e-af7b97d80480.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [1709]

**Additional context**
None.

**Comment by tmfksoft** [comment]
This is still present in our "canary" builds but in the public release branch it has been replaced with the welcome flow.
![image](https://user-images.githubusercontent.com/4118296/134755921-f9aa8701-cb9b-4d2b-8faa-a6f18ef595ae.png)

This will be added to the canary build for certain, so I'll close this.
