### ISSUE TITLE
Default screen selection not working.

### ISSUE THREAD

**Issue by Karbzee** [xeonr/sagl-launcher#48]
The default screen is not saving properly.

As you can see in the screenshot below, I have selected 'servers' as the default launch screen.

![server_selected_main_screen](https://user-images.githubusercontent.com/74452851/126633679-db7af21f-5e74-4dab-9b3d-6386b6b79dfc.PNG)

After closing/relaunching, I am not greeted by the default screen I have selected.
![Relaunch_sagl](https://user-images.githubusercontent.com/74452851/126633875-b7148421-f9c1-4714-991f-a6b13e6b8de8.PNG)

Instead I am greeted by default 'news tab'
![news_tab_selected_not_server_tab](https://user-images.githubusercontent.com/74452851/126633915-79eb4fa8-b053-448f-9b4f-e4afc80828cb.PNG)

**Comment by tmfksoft** [comment]
This should be resolved in the latest version and definitely so in the public release.
I'll close it as resolved for now, reopen it if you see the issue in 1.1.3 or above.
